apiVersion: v1
kind: Service
metadata:
  name: nebula-gateway
  labels:
    app: nebula-grid
    component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: 3000
  selector:
    app: nebula-grid
    component: gateway
